/* ===========================================================================
   Bundled example molecule
   ===========================================================================
   A small all-atom structure ("L1": a primary amide / alkyl chain / aryl
   ether / pyridine-containing molecule) plus its hand-curated reference CG
   mapping, loaded by the "Load example" button (see main.js) so the app has
   something to demonstrate on without requiring the user to bring their own
   file first. EXAMPLE_MAPPING is in the same Shaker dict-literal format
   generatePythonAssignments produces and parseShakerMapping reads
   (fileformats.js) — applied automatically right after the structure loads. */
export const EXAMPLE_PDB = `REMARK    GENERATED BY TRJCONV
TITLE     Generated by trjconv t=   0.00000 step= 0
REMARK    THIS IS A SIMULATION BOX
CRYST1   44.047   35.830   34.779  90.00  90.00  90.00 P 1           1
MODEL        1
ATOM      1  C00  L1     1      31.990  14.600   9.670  1.00  0.00
ATOM      2  C01  L1     1      31.690  15.980   9.090  1.00  0.00
ATOM      3  C02  L1     1      31.200  13.420   9.120  1.00  0.00
ATOM      4  C03  L1     1      31.730  12.040   9.530  1.00  0.00
ATOM      5  C04  L1     1      30.990  10.850   8.920  1.00  0.00
ATOM      6  C05  L1     1      31.590   9.510   9.320  1.00  0.00
ATOM      7  C06  L1     1      30.590   8.400   9.010  1.00  0.00
ATOM      8  N07  L1     1      29.590   8.100   9.830  1.00  0.00
ATOM      9  O08  L1     1      30.720   7.770   7.960  1.00  0.00
ATOM     10  C09  L1     1      32.400  17.200   9.680  1.00  0.00
ATOM     11  C0A  L1     1      31.900  17.530  11.090  1.00  0.00
ATOM     12  O0B  L1     1      32.500  18.730  11.510  1.00  0.00
ATOM     13  C0C  L1     1      32.090  19.070  12.770  1.00  0.00
ATOM     14  C0D  L1     1      33.080  19.330  13.730  1.00  0.00
ATOM     15  C0E  L1     1      32.650  19.910  14.930  1.00  0.00
ATOM     16  C0F  L1     1      31.270  20.050  15.140  1.00  0.00
ATOM     17  N0G  L1     1      30.350  19.610  14.270  1.00  0.00
ATOM     18  C0H  L1     1      30.730  19.200  13.050  1.00  0.00
ATOM     19  H0I  L1     1      34.140  19.120  13.650  1.00  0.00
ATOM     20  H0J  L1     1      33.370  20.270  15.650  1.00  0.00
ATOM     21  H0K  L1     1      31.010  20.420  16.120  1.00  0.00
ATOM     22  H0M  L1     1      29.910  19.090  12.350  1.00  0.00
ATOM     23  H0N  L1     1      30.820  17.640  10.990  1.00  0.00
ATOM     24  H0O  L1     1      31.990  16.720  11.820  1.00  0.00
ATOM     25  H0P  L1     1      33.450  17.010   9.850  1.00  0.00
ATOM     26  H0Q  L1     1      32.350  18.070   9.020  1.00  0.00
ATOM     27  H0R  L1     1      31.940  15.860   8.030  1.00  0.00
ATOM     28  H0S  L1     1      30.610  16.080   9.070  1.00  0.00
ATOM     29  H0T  L1     1      31.750  14.630  10.730  1.00  0.00
ATOM     30  H0U  L1     1      33.050  14.360   9.580  1.00  0.00
ATOM     31  H0V  L1     1      31.310  13.430   8.030  1.00  0.00
ATOM     32  H0W  L1     1      30.170  13.640   9.400  1.00  0.00
ATOM     33  H0X  L1     1      32.780  11.890   9.290  1.00  0.00
ATOM     34  H0Y  L1     1      31.590  11.870  10.600  1.00  0.00
ATOM     35  H0Z  L1     1      31.040  10.890   7.830  1.00  0.00
ATOM     36  H10  L1     1      29.960  10.960   9.270  1.00  0.00
ATOM     37  H11  L1     1      32.550   9.420   8.820  1.00  0.00
ATOM     38  H12  L1     1      31.780   9.390  10.390  1.00  0.00
ATOM     39  H13  L1     1      28.910   7.390   9.570  1.00  0.00
ATOM     40  H14  L1     1      29.330   8.750  10.560  1.00  0.00
TER
ENDMDL
`;

export const EXAMPLE_MAPPING = `mapping = {
    ## resname
    "L1": {
    ## bead name; type(opt.);   charge(opt.);         Mapping.
        "R11":  {"type": "SP2",  "charge": 0, "atoms": ['C06','O08','N07','H13']},
        "LR":   {"type": "C1",   "charge": 0, "atoms": ['C05','C04','C03','C02']},
        "LWR":  {"type": "C1",   "charge": 0, "atoms": ['C00','C01','C09','C0A']},
        "WR11": {"type": "SN2a", "charge": 0, "atoms": ['C0C','O0B','C0D','H0I']},
        "WR10": {"type": "TN6a", "charge": 0, "atoms": ['C0H','N0G','H0M']},
        "WR9":  {"type": "TC5e", "charge": 0, "atoms": ['C0E','C0F']},
    },
}
`;
